/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    AttachmentManager: typeof import('./components/MyTasksComponent/AttachmentManager.vue')['default']
    AudioConverter: typeof import('./components/AudioComponent/AudioConverter.vue')['default']
    AudioRecordDialog: typeof import('./components/AudioComponent/AudioRecordDialog.vue')['default']
    AudioUploadDialog: typeof import('./components/AudioComponent/AudioUploadDialog.vue')['default']
    Board23: typeof import('./components/MyTasksComponent/Board2-3.vue')['default']
    Board31: typeof import('./components/MyTasksComponent/Board3-1.vue')['default']
    CreateNewProjectDialog: typeof import('./components/HomepageComponent/CreateNewProjectDialog.vue')['default']
    DeleteDialog: typeof import('./components/MyTasksComponent/DeleteDialog.vue')['default']
    KanbanBoard: typeof import('./components/MyTasksComponent/KanbanBoard.vue')['default']
    ManagerReviewApproveAllDialog: typeof import('./components/ManagerReviewComponent/ManagerReviewApproveAllDialog.vue')['default']
    ManagerReviewCreateTaskDialog: typeof import('./components/ManagerReviewComponent/ManagerReviewCreateTaskDialog.vue')['default']
    MinuteDisplay: typeof import('./components/MinutesComponent/MinuteDisplay.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sidebar: typeof import('./components/HomepageComponent/Sidebar.vue')['default']
    Sidebar3: typeof import('./components/HomepageComponent/Sidebar3.vue')['default']
    Stage23: typeof import('./components/MyTasksComponent/Stage2-3.vue')['default']
    Stage31: typeof import('./components/MyTasksComponent/Stage3-1.vue')['default']
    TaskCard23: typeof import('./components/MyTasksComponent/TaskCard2-3.vue')['default']
    TaskDetail: typeof import('./components/MyTasksComponent/TaskDetail.vue')['default']
    TaskDraft: typeof import('./components/ManagerReviewComponent/TaskDraft.vue')['default']
    'TaskDraft(Deprecated)': typeof import('./components/ManagerReviewComponent/TaskDraft(Deprecated).vue')['default']
    TaskDraftApproveOneTaskButton: typeof import('./components/ManagerReviewComponent/TaskDraftApproveOneTaskButton.vue')['default']
    TaskDraftDeleteOneTaskButton: typeof import('./components/ManagerReviewComponent/TaskDraftDeleteOneTaskButton.vue')['default']
    TaskDraftEditOneTaskButton: typeof import('./components/ManagerReviewComponent/TaskDraftEditOneTaskButton.vue')['default']
    Topbar: typeof import('./components/HomepageComponent/Topbar.vue')['default']
    TranscriptChatbot: typeof import('./components/TranscriptChatbot.vue')['default']
    TranscriptDisplay: typeof import('./components/TranscriptComponent/TranscriptDisplay.vue')['default']
    Uploadfile: typeof import('./components/AudioComponent/Uploadfile.vue')['default']
    UploadFileCustom: typeof import('./components/AudioComponent/UploadFileCustom.vue')['default']
    VConfirmEdit: typeof import('./components/VConfirmEdit.vue')['default']
    VuetifyTaskModal6: typeof import('./components/MyTasksComponent/VuetifyTaskModal6.vue')['default']
  }
}
