/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ActionButtonsBar: typeof import('./components/ActionButtonsBar.vue')['default']
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    ApproveButtonDialogue: typeof import('./components/ApproveButtonDialogue.vue')['default']
    AudioConverter: typeof import('./components/AudioConverter.vue')['default']
    copy: typeof import('./components/KanbanRow3 copy.vue')['default']
    DeleteButtonDialogue: typeof import('./components/DeleteButtonDialogue.vue')['default']
    DownloadButton: typeof import('./components/Buttons/DownloadButton.vue')['default']
    EditButton: typeof import('./components/Buttons/EditButton.vue')['default']
    EditTaskDialog: typeof import('./components/EditTaskDialog.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    KanbanButton: typeof import('./components/Buttons/KanbanButton.vue')['default']
    KanbanRow: typeof import('./components/KanbanRow.vue')['default']
    KanbanRow2: typeof import('./components/KanbanRow2.vue')['default']
    KanbanRow3: typeof import('./components/KanbanRow3.vue')['default']
    KanbanRow4: typeof import('./components/KanbanRow4.vue')['default']
    Lightbulb: typeof import('./components/Lightbulb.vue')['default']
    MinuteDisplay: typeof import('./components/MinuteDisplay.vue')['default']
    MinutesButton: typeof import('./components/Buttons/MinutesButton.vue')['default']
    MyAppBar: typeof import('./components/MyAppBar.vue')['default']
    Navbar: typeof import('./components/Navbar.vue')['default']
    NavbarManagerReview: typeof import('./components/NavbarManagerReview.vue')['default']
    PopUpConfirmDelete: typeof import('./components/PopUpConfirmDelete.vue')['default']
    ProjectBoards: typeof import('./components/ProjectBoards.vue')['default']
    ProjectBoards2: typeof import('./components/ProjectBoards2.vue')['default']
    ProjectBoards4: typeof import('./components/ProjectBoards4.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ShareButton: typeof import('./components/Buttons/ShareButton.vue')['default']
    Sidebar: typeof import('./components/Sidebar.vue')['default']
    TaskDraft: typeof import('./components/TaskDraft.vue')['default']
    TasklistButton: typeof import('./components/Buttons/TasklistButton.vue')['default']
    TranscriptButton: typeof import('./components/Buttons/TranscriptButton.vue')['default']
    TranscriptDisplay: typeof import('./components/TranscriptDisplay.vue')['default']
    VuetifyTaskModal6: typeof import('./components/VuetifyTaskModal6.vue')['default']
  }
}
