/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ActionButtonsBar: typeof import('./components/ActionButtonsBar.vue')['default']
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    AudioConverter: typeof import('./components/AudioComponent/AudioConverter.vue')['default']
    CreateNewKanbanTaskButton: typeof import('./components/createNewKanbanTaskButton.vue')['default']
    CreateNewKanbanTaskDialog: typeof import('./components/createNewKanbanTaskDialog.vue')['default']
    DownloadButton: typeof import('./components/MinutesComponent/DownloadButton.vue')['default']
    EditButton: typeof import('./components/MinutesComponent/EditButton.vue')['default']
    KanbanBoard: typeof import('./components/kanbanBoard.vue')['default']
    KanbanButton: typeof import('./components/MinutesComponent/KanbanButton.vue')['default']
    KanbanList: typeof import('./components/kanbanList.vue')['default']
    KanbanRow: typeof import('./components/KanbanRow.vue')['default']
    KanbanRow2: typeof import('./components/KanbanRow2.vue')['default']
    KanbanRow3: typeof import('./components/KanbanRow3.vue')['default']
    KanbanRow4: typeof import('./components/KanbanRow4.vue')['default']
    Lightbulb: typeof import('./components/Lightbulb.vue')['default']
    ManagerReviewNavbar: typeof import('./components/ManagerReviewComponent/ManagerReviewNavbar.vue')['default']
    ManagerReviewNavbarApproveAllButton: typeof import('./components/ManagerReviewComponent/ManagerReviewNavbarApproveAllButton.vue')['default']
    ManagerReviewNavbarCreateButton: typeof import('./components/ManagerReviewComponent/ManagerReviewNavbarCreateButton.vue')['default']
    ManagerReviewNavbarCreateTaskDialog: typeof import('./components/ManagerReviewComponent/ManagerReviewNavbarCreateTaskDialog.vue')['default']
    MinuteDisplay: typeof import('./components/MinutesComponent/MinuteDisplay.vue')['default']
    MinutesButton: typeof import('./components/TranscriptComponent/MinutesButton.vue')['default']
    MyAppBar1: typeof import('./components/AudioComponent/MyAppBar1.vue')['default']
    MyAppBar2: typeof import('./components/MinutesComponent/MyAppBar2.vue')['default']
    MyAppBar3: typeof import('./components/TranscriptComponent/MyAppBar3.vue')['default']
    Navbar: typeof import('./components/AudioComponent/Navbar.vue')['default']
    NavbarKanban: typeof import('./components/NavbarKanban.vue')['default']
    NavbarMyTasks: typeof import('./components/NavbarMyTasks.vue')['default']
    PopUpConfirmDelete: typeof import('./components/ManagerReviewComponent/PopUpConfirmDelete.vue')['default']
    ProjectBoards: typeof import('./components/ProjectBoards.vue')['default']
    ProjectBoards2: typeof import('./components/ProjectBoards2.vue')['default']
    ProjectBoards4: typeof import('./components/ProjectBoards4.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ShareButton: typeof import('./components/MinutesComponent/ShareButton.vue')['default']
    Sidebar: typeof import('./components/Sidebar.vue')['default']
    TaskDraft: typeof import('./components/ManagerReviewComponent/TaskDraft.vue')['default']
    TaskDraftApproveOneTaskButton: typeof import('./components/ManagerReviewComponent/TaskDraftApproveOneTaskButton.vue')['default']
    TaskDraftDeleteOneTaskButton: typeof import('./components/ManagerReviewComponent/TaskDraftDeleteOneTaskButton.vue')['default']
    TaskDraftEditOneTaskButton: typeof import('./components/ManagerReviewComponent/TaskDraftEditOneTaskButton.vue')['default']
    TasklistButton: typeof import('./components/MinutesComponent/TasklistButton.vue')['default']
    TranscriptButton: typeof import('./components/MinutesComponent/TranscriptButton.vue')['default']
    TranscriptDisplay: typeof import('./components/TranscriptComponent/TranscriptDisplay.vue')['default']
    Uploadfile: typeof import('./components/AudioComponent/Uploadfile.vue')['default']
    VuetifyTaskModal6: typeof import('./components/VuetifyTaskModal6.vue')['default']
  }
}
