/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/AudioInput': RouteRecordInfo<'/AudioInput', '/AudioInput', Record<never, never>, Record<never, never>>,
    '/Homepage': RouteRecordInfo<'/Homepage', '/Homepage', Record<never, never>, Record<never, never>>,
    '/Kanban-2': RouteRecordInfo<'/Kanban-2', '/Kanban-2', Record<never, never>, Record<never, never>>,
    '/Kanban-3': RouteRecordInfo<'/Kanban-3', '/Kanban-3', Record<never, never>, Record<never, never>>,
    '/Loginpage': RouteRecordInfo<'/Loginpage', '/Loginpage', Record<never, never>, Record<never, never>>,
    '/ManagerReview': RouteRecordInfo<'/ManagerReview', '/ManagerReview', Record<never, never>, Record<never, never>>,
    '/MinutesHomepage': RouteRecordInfo<'/MinutesHomepage', '/MinutesHomepage', Record<never, never>, Record<never, never>>,
    '/MyTasksPage2': RouteRecordInfo<'/MyTasksPage2', '/MyTasksPage2', Record<never, never>, Record<never, never>>,
    '/MyTasksPage2-2': RouteRecordInfo<'/MyTasksPage2-2', '/MyTasksPage2-2', Record<never, never>, Record<never, never>>,
    '/TranscriptsHomepage': RouteRecordInfo<'/TranscriptsHomepage', '/TranscriptsHomepage', Record<never, never>, Record<never, never>>,
  }
}
