/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/Homepage': RouteRecordInfo<'/Homepage', '/Homepage', Record<never, never>, Record<never, never>>,
    '/KanbanPage': RouteRecordInfo<'/KanbanPage', '/KanbanPage', Record<never, never>, Record<never, never>>,
    '/ManagerReview': RouteRecordInfo<'/ManagerReview', '/ManagerReview', Record<never, never>, Record<never, never>>,
    '/MinutesHomepage': RouteRecordInfo<'/MinutesHomepage', '/MinutesHomepage', Record<never, never>, Record<never, never>>,
    '/MyTasks': RouteRecordInfo<'/MyTasks', '/MyTasks', Record<never, never>, Record<never, never>>,
    '/MyTasks2': RouteRecordInfo<'/MyTasks2', '/MyTasks2', Record<never, never>, Record<never, never>>,
    '/MyTasks3': RouteRecordInfo<'/MyTasks3', '/MyTasks3', Record<never, never>, Record<never, never>>,
    '/MyTasks4': RouteRecordInfo<'/MyTasks4', '/MyTasks4', Record<never, never>, Record<never, never>>,
    '/TestTaskModal': RouteRecordInfo<'/TestTaskModal', '/TestTaskModal', Record<never, never>, Record<never, never>>,
    '/TranscriptsHomepage': RouteRecordInfo<'/TranscriptsHomepage', '/TranscriptsHomepage', Record<never, never>, Record<never, never>>,
  }
}
