from typing import List, TypedDict

class ReWOO(TypedDict):
    # The initial task description
    task: str

    # The big-chunk plan string generated by the planner
    plan_string: str

    # The step-by-step plan extracted from plan_string
    steps: List[str]

    # Intermediate results after tool calls
    results: dict

    result: str # equivalent to autostart

    # A list of file paths retrieved by the search tool
    retrieved_docs: List[str]

    # The content generated by the autostart tool
    autostart_content: str